#!/bin/sh

# Use xwinwrap-git from AUR (https://github.com/takase1121/xwinwrap)

var=$(cat $HOME/.config/video-wallpapers/wallpaperVar)
wallpapernum=$(ls $HOME/.config/video-wallpapers/wallpapers | wc -l)
new=$(($var + 1)) # Increment the wallpaper number

if [[ $1 != "startup" ]]; then
    # If the script is not called on startup, then increment the wallpaper number
    if [[ $1 =~ ^[0-9]+$ ]] && [[ -f $HOME/.config/video-wallpapers/wallpapers/$1.mp4 || -f $HOME/.config/video-wallpapers/wallpapers/$1.gif ]]; then
      var=$1
    elif [[ $var -ge $wallpapernum ]]; then
        var=1
    else
        var=$new
    fi
    echo $var >$HOME/.config/video-wallpapers/wallpaperVar
else
    var=$(($var - 1))
    if [ $var -eq 0 ]; then
        var=$wallpapernum
    fi
fi

# if current shell is gnome or cinnamon or herbstluftwm, set args=$(-fs -ni -nf -b -un -fdt)
# else set args=$(-fs -ni -nf -b -un -ov -fdt)

if [[ $(echo $XDG_SESSION_DESKTOP | grep -Eo 'gnome|cinnamon|herbstluftwm') ]]; then
    args="-fs -ni -nf -b -un -fdt"
else
    args="-fs -ni -nf -b -un -ov -fdt"
fi

pkill -9 mpv
pkill -9 gifview

if [[ $(ls $HOME/.config/video-wallpapers/wallpapers | grep $var.mp4) ]]; then
    # Use mpv to play mp4 if current wallpaper is .mp4
    sleep 0.01
    xwinwrap $args -- mpv -wid %WID -quiet --no-audio $HOME/.config/video-wallpapers/wallpapers/$var.mp4 -loop >/dev/null &
else
    if [[ $(ls $HOME/.config/video-wallpapers/wallpapers | grep $var.gif) ]]; then
        # Use gifview to play gif if current wallpaper is .gif
        sleep 0.01
        xwinwrap $args -- gifview -w %WID $HOME/.config/video-wallpapers/wallpapers/$var.gif --geometry 2560x1440 -a >/dev/null &
    fi
fi

#else if [[ $(ls $HOME/.config/video-wallpapers/wallpapers/$var | grep .html) ]] # implement html wallpaper
